In [1]:
# change the working directory to point to the root directory
import os

os.chdir("../")

In [2]:
# imports
import numpy as np
import pandas as pd

In [3]:
# imports
import numpy as np
import pandas as pd
# imports for plots
from plotly import graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio

pio.templates.default = "plotly_white"

In [26]:
df_multi_clustering = pd.DataFrame()

dir_name = "processed_data/individual_regions/"
for file in os.listdir(dir_name):
    # region lat and lon
    lat, lon, _, _ = file[:-4].split(";")

    # info region
    dict_region = np.load(dir_name + file, allow_pickle='TRUE').item()

    nb_clusters_multi = dict_region["multivariate"]["nb_clusters"]
    # weather_var, nb_cluster_uni, _ = max([(key, val['nb_clusters'], val["score"]) for key, val in dict_region["univariate"].items()], key=lambda x: x[2])

    dict_row = {"lat": [lat], "lon": [lon], "multi_nb_clusters": [nb_clusters_multi]}

    for weather_var in dict_region["univariate"]:
        dict_row[f"{weather_var}_score"] = [dict_region["univariate"][weather_var]["score"]]
        dict_row[f"{weather_var}_nb_clusters"] = [dict_region["univariate"][weather_var]["nb_clusters"]]

    df_multi_clustering = df_multi_clustering.append(pd.DataFrame(dict_row), ignore_index=True)

In [27]:
# save data
df_multi_clustering.to_csv("processed_data/summary_clustering.csv", index=False)

In [28]:
df_multi_clustering

,lat,lon,multi_nb_clusters,cumulative_GDD_score,cumulative_GDD_nb_clusters,cumulative_PRECTOT_score,cumulative_PRECTOT_nb_clusters,cumulative_WS2M_score,cumulative_WS2M_nb_clusters,cumulative_RH2M_score,cumulative_RH2M_nb_clusters
0,21.491028281152968,-13.571798288799789,2,39.701617,3,298.549049,9,61.076928,4,71.545236,3
1,21.491028281152968,-13.87179828879979,2,39.701617,3,298.549049,9,61.076928,4,71.545236,3
2,21.491028281152968,-14.171798288799788,2,37.108958,6,222.368448,9,71.034151,3,80.824550,2
3,21.491028281152968,-14.47179828879979,2,37.108958,6,222.368448,9,71.034151,3,80.824550,2
4,21.491028281152968,-14.771798288799788,6,39.896292,2,254.187469,9,71.099992,3,73.191266,2
...,...,...,...,...,...,...,...,...,...,...,...
700,35.29102828115297,-5.77179828879979,2,37.713482,4,70.136843,2,45.420252,3,51.801998,3
701,35.29102828115297,-6.071798288799791,2,54.132288,2,72.981634,2,44.960993,4,64.366716,3
702,35.591028281152965,-5.471798288799791,2,50.553839,4,53.597931,5,45.201880,2,54.432850,5
703,35.591028281152965,-5.77179828879979,2,50.405874,6,60.664443,2,51.601102,2,54.495385,2
704,35.89102828115297,-5.471798288799791,2,50.553839,4,53.597931,5,45.201880,2,54.432850,5

In [22]:
# map
fig = px.scatter_geo(
    df_multi_clustering,
    lat="lat", lon="lon",
    color="multi_nb_clusters"
    )

fig.show(renderer="notebook")

In [30]:
df_multi_clustering.drop(labels=["lat", "lon"], axis=1).describe()

,multi_nb_clusters,cumulative_GDD_score,cumulative_GDD_nb_clusters,cumulative_PRECTOT_score,cumulative_PRECTOT_nb_clusters,cumulative_WS2M_score,cumulative_WS2M_nb_clusters,cumulative_RH2M_score,cumulative_RH2M_nb_clusters
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,2.692199,44.989305,3.113475,95.356633,4.527660,49.803977,2.455319,60.994997,2.929078
std,0.906265,6.566517,1.507991,82.605268,2.746307,15.203434,0.733573,11.052187,1.349692
min,2.000000,31.639630,2.000000,33.795091,2.000000,23.383118,2.000000,38.999318,2.000000
25%,2.000000,40.575967,2.000000,49.678637,2.000000,38.183135,2.000000,53.078014,2.000000
50%,2.000000,43.378144,3.000000,60.852942,3.000000,47.818842,2.000000,60.312682,2.000000
75%,3.000000,48.311578,4.000000,83.567586,7.000000,58.856326,3.000000,69.024295,3.000000
max,9.000000,77.884811,9.000000,440.836154,9.000000,96.749022,6.000000,91.193416,9.000000